### ISSUE TITLE
Errata 1.2 tracking

### ISSUE THREAD

**Issue by ThePants999** [RosterizerTestData/Warhammer40k10e#133]
# ADEPTA SORORITAS
- [x] Mortifiers – Abilities, Anguish of the Unredeemed
Change to ‘Each time this unit makes a Charge move, until the end of
the turn, melee weapons equipped by models in this unit have the
[SUSTAINED HITS 1] ability.’
- [x] Dominion Squad – Ranged Weapons, boltgun
Add ‘[ASSAULT, RAPID FIRE 1].’
# ADEPTUS CUSTODES
- [x] Anathema Psykana Rhino – Core Abilities
Add ‘Firing Deck 2’.
- [x]  Knight-Centura – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 3 3+ 4 0 1
- [x] Knight-Centura – Wargear Options
Change sub-bullets to:
■ 1 master-crafted boltgun and 1 close combat weapon
■ 1 Witchseeker flamer and 1 close combat weapon
# ADEPTUS MECHANICUS
- [x] Onager Dunecrawler – Ranged Weapons
Delete the heavy phosphor blaster profile.
# AELDARI
- [x] Autarch – Ranged Weapons, Reaper launcher – starswarm
Change Damage to ‘1’.
- [x] Autarch – Wargear Options
Change to:
‘This model’s shuriken pistol can be replaced with one of the following:
■ 1 death spinner
■ 1 Dragon fusion gun
■ 1 fusion pistol
■ 1 Reaper launcher
This model’s star glaive can be replaced with one of the following:
■ 1 Banshee blade
■ 1 Scorpion chainsword
This model can be equipped with one of the following:
■ 1 Howling Banshee mask
■ 1 mandiblasters’
- [x] Autarch Wayleaper – Ranged Weapons, Reaper launcher – starswarm
Change Damage to ‘1’.
- [x] Autarch Wayleaper – Wargear Options
Change to:
‘This model’s shuriken pistol can be replaced with one of the following:
■ 1 death spinner
■ 1 Dragon fusion gun
■ 1 fusion pistol
■ 1 Reaper launcher
This model’s star glaive can be replaced with one of the following:
■ 1 Banshee blade
■ 1 Scorpion chainsword
This model can be equipped with one of the following:
■ 1 Howling Banshee mask
■ 1 mandiblasters’
- [x] Corsair Voidreavers – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 3 3+ 3 0 1
- [x] Corsair Voidreavers – Unit Composition, wargear lists
Change to:
‘■ Every model is equipped with: shuriken pistol; close combat
weapon; Aeldari power sword.’
- [x] Corsair Voidscarred – Ranged Weapons, fusion pistol
Change Damage to ‘D3’.
- [x] Corsair Voidscarred – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 3 3+ 3 0 1
- [x] Corsair Voidscarred – Unit Composition, wargear lists
Change to:
‘■ Every Corsair Voidscarred and Voidscarred Felarch is equipped
with: shuriken pistol; Aeldari power sword; close combat weapon.
■ A Shade Runner is equipped with: shuriken pistol; close combat
weapon; paired Hekatarii blades.
■ A Soul Weaver is equipped with: shuriken pistol; Aeldari power sword;
close combat weapon; channeller stones.
■ A Way Seeker is equipped with: shuriken pistol; Executioner; close
combat weapon; witch staff.’
- [x] Dark Reapers – Unit Composition, 3rd line
Change to ‘Every model is equipped with: Reaper launcher; close
combat weapon.’
- [x] Detachment Rule Card – Ynnari section, last paragraph
Change to:
‘No Drukhari models included in your army in this way can be given
Enhancements. You cannot include units with any of the following
keywords in your army using these rules: Phoenix Lords; Avatar of
Khaine; Solitaire; Haemonculus Covens.’
- [x] Dire Avengers – Unit Composition, 3rd line
Change to ‘Every model is equipped with: Avenger shuriken catapult;
close combat weapon.’
- [x] Solitaire – Abilities, Blitz
Change to:
‘Blitz: Once per battle, in your Movement phase, this model can use
this ability before it makes a Normal move. If it does, until the end of
the turn, add 2D6" to this model’s Move characteristic and add 3 to the
Attacks characteristic of this model’s Solitaire weapons.’
- [x] Spiritseer – Abilities, Tears of Isha
Change to:
‘While this model is leading a unit, in your Command phase, you can
return 1 destroyed Bodyguard model to that unit.’
- [x] Storm Guardians – Wargear Options, 1st and 2nd bullets
Change to:
‘■ Up to 2 Storm Guardians can each have their shuriken pistol replaced
with 1 Aeldari flamer.
■ Up to 2 Storm Guardians can each have their shuriken pistol replaced
with 1 Guardian fusion gun.’
- [x] Stratagems Card – Phantasm Stratagem, Target section
Change to:
‘TARGET: One Aeldari unit from your army (excluding Aircraft).’
- [x] Striking Scorpions – Wargear Options, 1st bullet
Change to:
‘■ The Striking Scorpion Exarch’s shuriken pistol can be replaced with 1
Scorpion’s claw.’
- [x] Wave Serpent – Ranged Weapons, twin starcannon
Change Attacks to ‘2’.
- [x] Wave Serpent – Abilities, Wave Serpent Shield
Change to:
‘Wave Serpent Shield: Once per battle, in your Shooting phase, you can
select one enemy unit that is within 12" of and visible to this model
and roll one D6: on a 2+, that enemy unit suffers D3 mortal wounds and
must take a Battle-shock test.’
- [x] Wraithguard – Abilities, War Construct
Delete the final sentence of this ability.
# AGENTS OF THE IMPERIUM
- [x] Rogue Trader Entourage – Keywords section
Delete ‘Retinue’.
# ASTRA MILITARUM
- [x] Aegis Defence Line
Add Deployment section, to read:
‘When this model is set up, it will consist of 1 platform section, up
to 5 shield sections, up to 2 broken shield sections and up to 2 end
sections. All sections must be connected to each other to form a
continuous defence line; the 2 broken shield sections can be placed
either at the end of the defence line, or in the middle of it such that
both are within ½" of each other (in this case, these 2 sections count
as being connected to each other). All of the sections that have been
set up are then treated as a single model for all rules purposes.’
- [x] Astra Militarum Infantry Armoury Card, asterisk note
Change to:
‘* If this weapon is equipped by a Militarum Tempestus model, it has a
Ballistic Skill characteristic of 3+.’
- [x] Astra Militarum Vehicle Armoury Card, exterminator autocannon,
weapon abilities
Change to:
‘[RAPID FIRE 4, TWIN-LINKED]’.
- [x] Death Korps of Krieg – Wargear Options
Change 2nd bullet to:
‘For every 10 models in this unit, 1 Death Korps Trooper’s lasgun can
be replaced with one of the following:
 ■ 1 lasgun and 1 vox-caster (that model’s lasgun cannot be replaced)
 ■ 1 plasma gun’
Add the following bullet:
‘■ 1 Death Korps Trooper equipped with a lasgun can be equipped with
1 Death Korps medi-pack (that model’s lasgun cannot be replaced).’
- [x] Infantry Squad – Unit Composition
Add the following:
‘Designer’s Note: Each Heavy Weapons Team model in this unit counts
as 2 models for the purposes of wargear options.’
- [x] Ogryn Bodyguard – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 4 3+ 6 0 1
- [x] Ogryn Bodyguard – Unit Composition, 2nd line
Change to ‘This model is equipped with: ripper gun; close combat
weapon; huge knife.’
- [x] Taurox Prime – Ranged Weapons, Taurox missile launcher (frag)
Change Strength to ‘4’.
- [x] Urusula Creed – Abilities, Tactical Genius
Change to:
‘Tactical Genius: Once per battle round, one Regiment unit from your
army within 12" of this model can be targeted with a Stratagem for 0CP,
even if another unit from your army has already been targeted with
that Stratagem this phase.’
# BLACK TEMPLARS
- [x] Castellan – Keywords section
Add ‘Lieutenant’.
- [x] High Marshal Helbrecht – Keywords section
Add ‘Chapter Master’.
- [x] Marshal – Keywords section
Add ‘Captain’.
- [x] Primaris Crusader Squad – Ranged Weapons, bolt pistol
Change Range to ‘12"’.
- [x] Primaris Crusader Squad – Wargear Options, 2nd bullet
Change to:
‘■ Any number of Primaris Neophytes can each have their bolt pistol
and Astartes chainsword replaced with 1 Neophyte firearm and 1
close combat weapon.’
- [x] Primaris Sword Brethren – Melee Weapons
Add twin lightning claws profile:
RANGE A WS S AP D
Twin lightning claws [TWIN-LINKED] Melee 5 3+ 5 -2 1
- [x] Primaris Sword Brethren – Wargear Options
Change 1st bullet to:
‘Any number of Primaris Sword Brothers can each have their Astartes
chainsword replaced with 1 power weapon.’
Add 6th bullet to read:
‘■ For every 5 models in this unit, 1 Primaris Sword Brother’s heavy
bolt pistol and Astartes chainsword can be replaced with 1 twin
lightning claws.’
- [x] Primaris Sword Brethren – Unit Composition, 2nd line
Change to ‘4-9 Primaris Sword Brothers’
# BLOOD ANGELS
- [x] Baal Predator – Core Abilities
Add ‘Deadly Demise D3’.
- [x] Death Company Dreadnought – Keywords section
Add ‘Dreadnought’.
- [x] Furioso Dreadnought – Keywords section
Add ‘Smoke’ and ‘Dreadnought’.
- [x] Librarian Dreadnought – Keywords section
Add ‘Smoke’ and ‘Dreadnought’.
# CHAOS DAEMONS
- [x] Blue Horrors – Abilities, Cackling Horrors
Change to:
‘While an enemy unit is within 6" of this unit, if this unit contains one or
more Blue Horror models, worsen the Leadership characteristic of
models in that enemy unit by 1.’
- [x] Burning Chariot – Keywords section
Add ‘Fly’.
- [x] Great Unclean One – Ranged Weapons, putrid vomit
Change Ballistic Skill to ‘N/A’.
# CHAOS SPACE MARINES
- [x] Chaos Lord in Terminator Armour – Wargear Options, 2nd bullet
Change to:
‘This model’s exalted weapon can be replaced with one of
the following:
■ 1 chainfist
■ 1 power fist’
- [x] Chaos Predator Destructor – Ranged Weapons, Predator autocannon
Add ‘[RAPID FIRE 2].’
- [x] Chaos Rhino – Core Abilities
Add ’Firing Deck 2’.
- [x] Chosen – Wargear Options, 2nd bullet
Change to:
‘For every 5 models in this unit, up to 2 models can each have their
boltgun replaced with 1 combi-weapon.’
- [x] Legionaries – Ranged Weapons, Havoc autocannon
Change Ballistic Skill to ‘4+’.
- [x] Legionaries – Wargear Options, 1st bullet, 1st sub-bullet
Change to:
‘ ■ 1 plasma pistol and 1 Astartes chainsword*’.
- [x] Traitor Guardsmen – Wargear Options, 1st bullet
Change to:
‘■ Up to 3 Traitor Guardsmen can each have their lasgun replaced with
one of the following (to a maximum of 2 of each per unit):’
# DARK ANGELS
- [x] Deathwing Command Squad – Wargear Options
Add new bullet to read:
‘■ 1 Deathwing Command Terminator’s power fist can be replaced with
1 power weapon.’
- [x] Deathwing Strikemaster – Leader section, 2nd bullet
Change to:
‘■ Deathwing Terminator Squad’.
# DEATH GUARD
- [x] Death Guard Chaos Lord – Ranged Weapons, plague bolt pistol
Add ‘[Pistol]’.
- [x] Death Guard Cultists – Ranged Weapons, heavy stubber
Change Ballistic Skill to ‘5+’.
- [x] Death Guard Daemon Prince with Wings – Core Abilities
Add ‘Deep Strike’.
- [x] Death Guard Helbrute – Abilities, Infused with the Blessings of Nurgle
Change the last sentence to ‘Until the start of your next turn, that
enemy unit is always considered to be within Contagion Range of
this model.’
- [x] Death Guard Sorcerer in Terminator Armour – Abilities,
Putrescent Vitality
Change to:
‘Putrescent Vitality (Psychic): At the start of the Fight phase, you can
roll one D6: on a 1, this Psyker’s unit suffers D3 mortal wounds; on
a 2+, until the end of the phase, each time an attack is allocated to a
model in this Psyker’s unit, subtract 1 from the Damage characteristic
of that attack.’
- [x] Malignant Plaguecaster – Ranged Weapons, plague bolt pistol
Add ‘[Pistol]’.
- [x] Plague Marines – Ranged Weapons, plague bolt pistol
Add ‘[Pistol]’.
- [x] Plague Surgeon – Ranged Weapons, plague bolt pistol
Add ‘[Pistol]’.
# DEATHWATCH
- [x] Fortis Kill Team – Ranged Weapons, storm bolter
Delete this weapon profile.
- [x] Kill Team Cassius – Melee Weapons, Long Vigil melee weapon
Change Attacks to ‘3’, Strength to ‘5’ and AP to ‘-2’.
- [x] Kill Team Cassius – Ranged Weapons, heavy flamer
Change Strength to ‘5’ and AP to ‘-1’.
- [x] Proteus Kill Team – Melee Weapons, Terminator thunder hammer
Change Attacks to ‘3’.
- [x] Proteus Kill Team – Ranged Weapons, twin boltgun
Change Attacks to ‘2’.
- [x] Spectrus Kill Team – Ranged Weapons, special-issue bolt pistol
Change Attacks to ‘1’.
- [x] Spectrus Kill Team – Wargear Options
Add the following bullets:
‘■ One model can replace its bolt sniper rifle with 1 bolt carbine.
■ Any number of models can each replace their bolt sniper rifle with 1
las fusil.
■ Any number of models can each replace their combat knife with 1
bolt carbine and 1 close combat weapon.’
# DRUKHARI
- [x] Voidraven Bomber – Keywords section
Add ‘Fly’.
- [x] Wyches – Ranged Weapons, splinter pistol
Change ‘[ANTI-INFANTRY 4+]’ to ‘[ANTI-INFANTRY 3+]’.
# GENESTEALER CULTS
- [x] Army Rule Card – Cult Ambush, 1st and 2nd paragraphs
Change to:
‘If your Army Faction is Genestealer Cults, each time a unit with
this ability is destroyed, roll one D6, adding 3 to the result if it is a
Battleline unit. On a 4+, add a new unit to your army identical to your
destroyed unit, in Cult Ambush, at its Starting Strength and with all of
its wounds remaining, and you can place one Cult Ambush marker*
anywhere on the battlefield that is more than 9" horizontally away
from all enemy units (if this is not possible, no marker is placed).
If an enemy model (excluding Aircraft models) ends any kind
of move within 9" of a Cult Ambush marker you placed, that Cult
Ambush marker is removed from the battlefield. At the end of the
Reinforcements step of your opponent’s next Movement phase, for
each of your Cult Ambush markers that is still on the battlefield, you
can select one unit from your army that is in Cult Ambush and set up
that unit on the battlefield more than 9" horizontally away from all
enemy models and with at least one model in that unit touching that
Cult Ambush marker and all other models placed wholly within 3" of
that Cult Ambush marker (that Cult Ambush marker is then removed
from the battlefield).’
- [x] Atalan Jackals – Abilities, Demolition Run
Change to:
‘Once per battle round, after this unit ends a Normal move, you can
select one enemy unit within 6" of and visible to this unit and roll one
D6 for each model in this unit: for each 4+, that enemy unit suffers 1
mortal wound.’
# GREY KNIGHTS
- [x] Brotherhood Chaplain – Core Abilities
Add ‘Leader’.
- [x] Grey Knights Land Raider Crusader – Profile line
Change Move characteristic to ‘12"’.
- [x] Grey Knights Land Raider Redeemer – Profile line
Change Move characteristic to ‘12"’.
- [x] Stratagems Card – Death from the Warp Stratagem, Effect section
Change to:
‘EFFECT: Until the end of the turn, ranged weapons equipped by
models in your unit have the [ASSAULT] ability and each time a model
in your unit makes an attack, add 1 to the Hit roll.’
# IMPERIAL KNIGHTS
- [x] Army Rule Card – Code Chivalric, 2nd paragraph
Change to:
‘If, at the start of any of your Command phases, your selected Oath’s
Deed is completed, your army becomes Honoured for the rest of the
battle and you gain 3CP (you can only gain CP in this way once per
battle, and CP gained in this way are an exemption to the Core Rules
that limit the maximum number of CP you can gain per battle round
to 1).’
- [x] Army Rule Card – Code Chivalric, Lay Low the Tyrant, Oath Ability
Change to:
‘Oath Ability: Each time this model is selected to shoot or fight, re-roll a
single Hit roll of 1 and re-roll a single Wound roll of 1.’
- [x] Stratagems Card – Squires’ Duty Stratagem, Effect section
Change to:
‘EFFECT: Until the end of the phase, when resolving attacks that
target that enemy unit, improve the Strength and Armour Penetration
characteristics of weapons equipped by those Armiger models by 1. If
your army is Honoured, until the end of the phase, add 1 to the Damage
characteristic of those weapons as well.’’
# LEAGUES OF VOTANN
- [x] Enhancements Card – Appraising Glare, 2nd sentence
Change to:
‘Until the start of your next Command phase, while an enemy unit is
within range of that objective marker, it counts as having one more
Judgement token than it actually has (to a maximum of 2).’
- [x] Uthâr the Destined – Abilities, Ancestral Fortune
Change to:
‘Once per turn, you can change one Hit roll or one Wound roll made for
this model to a 6.’
# NECRONS
- [x] Cryptothralls – Abilities, Systematic Vigour
Change to:
‘Each time a Cryptothrall model in this unit is destroyed by a melee
attack, if that model has not fought this phase, roll one D6: on a 3+,
do not remove it from play. The destroyed model can fight after the
attacking model’s unit has finished making its attacks, and it is then
removed from play.’
- [x] Obelisk – Abilities, Gravitic Pulse, 2nd sentence
Change to:
‘Until the end of the turn, subtract 2" from the Move characteristic of
models in that unit and subtract 2 from Advance and Charge rolls made
for that unit.’
- [x] The Silent King – Core Abilities
Change to:
‘CORE: Deadly Demise D6+3 (Szarekh model only)’.
- [x] Transcendent C’tan – Abilities
Add Faction section to read:
‘FACTION: Reanimation Protocols’.
# ORKS
- [x] Battlewagon – Ranged Weapons, killkannon
Add the [BLAST] ability.
- [x] Big Mek in Mega Armour – Keywords section
Add ‘Mega Armour’.
- [x] Burna-bommer – Ranged Weapons, twin big shoota
Change Range to ‘36"’.
- [x] Deffkilla Wartrike – Keywords section
Add ‘Character’.
- [x] Gorkanaut – Ranged Weapons, twin big shoota
Change Range to ‘36"’.
- [x] Gretchin – Abilities, Runtherd
Change to:
‘While this unit contains one or more Gretchin models, each time an
attack targets this unit, Runtherd models in this unit have a Toughness
characteristic of 2.’
- [x] Meganobz – Keywords section
Add ‘Mega Armour’.
- [x] Megatrakk Scrapjet – Ranged Weapons, twin big shoota
Change Range to ‘36"’.
- [x] Morkanaut – Ranged Weapons, twin big shoota
Change Range to ‘36"’.
- [x] Stompa – Ranged Weapons, twin big shoota
Change Range to ‘36"’.
- [x] Stratagems Card – Mob Rule, Effect section
Change to:
‘EFFECT: Until the start of your next Command phase, while a friendly
Orks Infantry unit is within 6" of that Mob unit, that Orks Infantry
unit can still be selected as the target of your Stratagems even if it
is Battle-shocked.’
- [x] Trukk – Transport section
Change to:
‘This model has a transport capacity of 12 Orks Infantry models.
Each Mega Armour model takes up the space of 2 models. It cannot
transport Jump Pack or Ghazghkull Thraka models.’
- [x] Warboss in Mega Armour – Keywords section
Add ‘Mega Armour’.
# SPACE MARINES
- [x] Adeptus Astartes Armoury Card
Add flamer profile:
RANGE A BS S AP D
Flamer [IGNORES COVER, TORRENT] 12" D6 N/A 4 0 1
Add grav-gun profile:
RANGE A BS S AP D
Grav-gun [ANTI-VEHICLE 2+] 18" 2 3+ 5 -1 2
Add meltagun profile:
RANGE A BS S AP D
Meltagun [MELTA 2] 12" 1 3+ 9 -4 D6
Add plasma gun profile:
RANGE A BS S AP D
Plasma gun – standard
[RAPID FIRE 1] 24" 1 3+ 7 -2 1
Plasma gun – supercharge
[HAZARDOUS, RAPID FIRE 1] 24" 1 3+ 8 -3 2
- [x] Assault Squad – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 2 3+ 4 0 1
- [x] Assault Squad – Wargear Options, 4th bullet
Change sub-bullets to:
‘■ 1 plasma pistol and 1 Astartes chainsword
■ 1 flamer and 1 close combat weapon
■ 1 meltagun and 1 close combat weapon
■ 1 plasma gun and 1 close combat weapon’
- [x] Assault Squad with Jump Pack – Melee Weapons
Add close combat weapon profile:
RANGE A WS S AP D
Close combat weapon Melee 2 3+ 4 0 1
- [x] Assault Squad with Jump Pack – Wargear Options, 4th bullet
Change sub-bullets to:
■ 1 plasma pistol and 1 Astartes chainsword
■ 1 flamer and 1 close combat weapon
■ 1 meltagun and 1 close combat weapon
■ 1 plasma gun and 1 close combat weapon
- [x] Ballistus Dreadnought – Keywords section
Add ‘Dreadnought’.
- [x] Bike Squad – Wargear Options, 3rd bullet
Change sub-bullets to:
‘■ 1 flamer*
■ 1 grav-gun*
■ 1 meltagun*
■ 1 plasma gun*
■ 1 plasma pistol’
- [x] Captain – Wargear Options, 1st bullet
Add the following sub-bullet:
‘■ 1 plasma pistol’.
- [x] Captain in Gravis Armour – Profile
Change Move characteristic to ‘5’.
- [x] Captain on Bike – Wargear Options, 1st bullet
Add the following sub-bullet:
‘■ 1 thunder hammer’
- [x] Captain with Jump Pack – Wargear Options, 1st bullet
Add the following sub-bullet:
‘■ 1 plasma pistol’
- [x] Chaplain with Jump Pack – Ranged Weapons, grav-pistol
Change Damage to ‘2’.
- [x] Command Squad – Ranged Weapons, grav-gun
Change Damage to ‘2’.
- [x] Command Squad – Wargear Options, 5th bullet
Add the following sub-bullet:
‘■ 1 plasma gun’
- [x] Contemptor Dreadnought – Keywords section
Add ‘Dreadnought’.
- [x] Librarian with Jump Pack – Core Abilities
Add ‘Deep Strike’.
- [x] Lieutenant – Wargear Options, 1st bullet
Add the following sub-bullet:
‘■ 1 grav-pistol’.
- [x] Redemptor Dreadnought – Keywords section
Add ‘Dreadnought’.
- [x] Reiver Squad – Wargear Options, 1st bullet
Change to:
‘■ All models in this unit can each have their combat knife replaced
with 1 bolt carbine and 1 close combat weapon.’
- [x] Scout Squad – Melee Weapons, power weapon
Change Strength to ‘5’.
- [x] Techmarine – Ranged Weapons, grav-pistol
Change Damage to ‘2’.
- [x] Techmarine – Wargear Options, 1st bullet
Add additional sub-bullet to read:
‘■ 1 grav-pistol’.
- [x] Vanguard Veteran Squad – Ranged Weapons, grav-pistol
Change Damage to ‘2’.
- [x] Vanguard Veteran Squad with Jump Packs – Ranged Weapons,
grav-pistol
Change Damage to ‘2’.
# SPACE WOLVES
- [x] Canis Wolfborn – Unit Composition, 2nd line
Change to:
‘This model is equipped with: bolt pistol; crushing teeth and jaws;
Wolf claws.’
- [x] Cyberwolf – Core Abilities
Add ‘Leader’.
- [x] Grey Hunters – Wargear Options
Add bullet to read:
‘■ 1 Grey Hunter’s bolt pistol can be replaced with 1 plasma pistol.’
- [x] Long Fangs – Faction Keywords section
Change to:
‘FACTION KEYWORDS: Adeptus Astartes, Space Wolves’.
- [x] Stormfang Gunship – Ranged Weapons,
helfrost destructor (focused)
Change Ballistic Skill to ‘N/A’.
- [x] Wolf Guard Terminators – Wargear Options
Change 7th sub-bullet of 1st bullet to read:
‘■ 1 storm shield*’
Change 2nd bullet to read:
‘For every 5 models in this unit, one Wolf Guard Terminator can replace
its storm bolter with one of the following:
■ 1 assault cannon
■ 1 heavy flamer
■ 1 storm bolter and 1 cyclone missile launcher (this model’s storm
bolter cannot be replaced)’.
- [x] Wolf Scouts – Profile line
Change Wounds characteristic to ‘2’.
# T’AU EMPIRE
- [x] Devilfish – Ranged Weapons, accelerator burst cannon
Change AP to ‘-1’.
- [x] Longstrike – Ranged Weapons, accelerator burst cannon
Change AP to ‘-1’.
- [x] Razorshark Strike Fighter – Ranged Weapons,
accelerator burst cannon
Change AP to ‘-1’.
- [x] Stealth Battlesuits – Unit Composition, 2nd line
Change to:
‘The Stealth Shas’vre is equipped with: burst cannon; battlesuit fists;
homing beacon.
Every Stealth Shas’ui model is equipped with: burst cannon;
battlesuit fists.’
- [x] Sun Shark Bomber – Ranged Weapons
Add missile pod profile:
RANGE A BS S AP D
Missile pod 30" 2 4+ 7 -1 2
- [x] Sun Shark Bomber – Unit Composition, 2nd line
Change to:
‘This model is equipped with: missile pod; 2 seeker missiles; 2 twin ion
rifles; armoured hull.’
- [x] Sun Shark Bomber – Wargear Options
Change to:
‘■ This model’s missile pod can be replaced with 1 twin missile pod.’
# THOUSAND SONS
Cabal of Sorcerers Army Rule – Temporal Surge
- [x] Thousand Sons Defiler – Ranged Weapons, twin lascannon
Change Strength to ‘12’.
- [x] Thousand Sons Land Raider – Ranged Weapons,
twin inferno heavy bolter
Change Range to ‘36"’ and Damage to ‘2’.
- [x] Thousand Sons Rhino – Core Abilities
Add ‘Firing Deck 2’.
- [x] Thousand Sons Rhino – Keywords section
Add ‘Dedicated Transport’.
# TYRANIDS
- [x] Barbgaunts – Abilities, Disruption Bombardment, 1st sentence
Change to:
‘In your Shooting phase, after this unit has shot, select one enemy
Infantry unit hit by one or more of those attacks made by this unit’s
bio-cannons. Until the end of your opponent’s next turn, that enemy
unit is disrupted.’
# WORLD EATERS
- [x] Enhancements Card – Favoured of Khorne, 2nd sentence
Change to:
‘Once per battle round, when you make a Blessings of Khorne roll,
before doing anything else, the bearer can use this Enhancement.’
- [x] World Eaters Rhino – Core Abilities
Add ‘Firing Deck 2’.
- [x] World Eaters Predator Destructor – Ranged Weapons,
Predator autocannon
Add ‘[RAPID FIRE 2]’.

**Comment by Nemo3823** [comment]
Done!
